import os
from bids import BIDSLayout
from pathlib import Path

configfile: "config/snakemake_config.yaml"

bidspath = Path("data/rawdata/bids")


if not bidspath.is_dir():
    rule all:
        input: #create bids directories based on subdirectories of dicompath (which correspond to field strengths)
            "data/rawdata/bidsify.done"
else: #create BIDSLayout for each subdirectory of bidspath (which correspond to field strengths)
    layout_dict = {}
    for field_strength in next(os.walk(bidspath))[1]:
        layout_dict[field_strength] = BIDSLayout(Path("data/rawdata/bids") / field_strength, validate = False)
    rule all:
        input: #do all preprocessing for each field strength
            "data/rawdata/bidsify.done",
            expand("data/derivatives/{field_strength}/MP2RAGE/MP2RAGE_stats.csv", field_strength=next(os.walk(bidspath))[1]),
            expand("data/derivatives/{field_strength}/ihmt/ihmt_stats.csv", field_strength=next(os.walk(bidspath))[1]),
            # expand("data/derivatives/{field_strength}/MP2RAGE/MP2RAGE_to_ihmt.done", field_strength=next(os.walk(bidspath))[1]),
            expand("data/derivatives/{field_strength}/ihmt/ihmt_to_freesurfer.done", field_strength=next(os.walk(bidspath))[1]),
            expand("data/derivatives/{field_strength}/freesurfer/qMT_stats.done", field_strength=next(os.walk(bidspath))[1]),
            expand("data/derivatives/{field_strength}/MP2RAGE/MP2RAGE_to_qMT.done", field_strength=next(os.walk(bidspath))[1]),
            expand("data/derivatives/{field_strength}/qMT/qMT_to_MP2RAGE.done", field_strength=next(os.walk(bidspath))[1]),
            expand("data/derivatives/{field_strength}/freesurfer/dwi_stats.done", field_strength=next(os.walk(bidspath))[1]),
            expand("data/derivatives/{field_strength}/MP2RAGE/MP2RAGE_to_DWI.done", field_strength=next(os.walk(bidspath))[1]),
            expand("data/derivatives/{field_strength}/dwi/DWI_to_MP2RAGE.done", field_strength=next(os.walk(bidspath))[1]),
            expand("data/derivatives/{field_strength}/QSM/derivatives/qsmxt/", field_strength=next(os.walk(bidspath))[1]),


include: "rules/B1map.smk"
include: "rules/bidsify.smk"
include: "rules/DWI.smk"
include: "rules/ihMT.smk"
include: "rules/MP2RAGE.smk"
include: "rules/multimodal_registration_segmentation.smk"
include: "rules/qMT.smk"
include: "rules/QSM.smk"