3T_system:
  poolFree_M0: 1.0
  poolFree_T1: 1.0
  poolFree_T2: 0.015
  poolFreeBound_exchangeRate: 21
  poolBound_M0: 0.16
  poolBound_T1: 1
  poolBound_T2: 0.00001
  poolBound_T1D: 0.01
  poolBound_lineshapeAsymmetry: 0

7T_system:
  poolFree_M0: 0.8435
  poolFree_T1: 2.0
  poolFree_T2: 0.025
  poolFreeBound_exchangeRate: 11
  poolBound_M0: 0.1565
  poolBound_T1: .5
  poolBound_T2: 0.00001056010813550731
  poolBound_T1D: 0.0020601
  poolBound_lineshapeAsymmetry: -594

custom_system:
  poolFree_M0: 1.0
  poolFree_T1: 1.450
  poolFree_T2: 0.015
  poolFreeBound_exchangeRate: 19
  poolBound_M0: 0.08
  poolBound_T1: 1
  poolBound_T2: 0.00001
  poolBound_T1D: 0.01
  poolBound_lineshapeAsymmetry: 0